// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedProductionCompaniesGenresList02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedProductionCompaniesGenresList02));
        
        string IMigrationMetadata.Id
        {
            get { return "201709252327452_addedProductionCompaniesGenresList02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
